### ISSUE TITLE
complexity calculation endpoints

### ISSUE THREAD

**Issue by davelandry** [Datawheel/logiclayer#2]
- [ ] ECI
- [ ] PCI
- [ ] RCA (@mcastillomolina)
- [ ] Proximity
- [ ] Relatedness
- [ ] Relative Relatedness
- [ ] Opportunity Gain

**Comment by alexandersimoes** [comment]
Progress: going slow.... working on "downloading" how logic layer will work to his head. Also looking into canon-stats to understand RCA / complexity calcs.

**Comment by alexandersimoes** [comment]
Let's have a discussion w/ @AlanORB to get optimal API design of query args.
